trigger:
- v2.0

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '10.x'

- script:
    npm install ./delete-adf-items/v2/ |
    npm run build ./delete-adf-items/v2/
  displayName: 'npm install & build delete-adf-items'

- script:
    npm install ./deploy-adf-json/v2/ |
    npm run build ./deploy-adf-json/v2/
  displayName: 'npm install & build deploy-adf-json'

- script:
    npm install ./toggle-adf-trigger/v2/ |
    npm run build ./toggle-adf-trigger/v2/
  displayName: 'npm install & build toggle-adf-trigger'

- script:
    npm install ./trigger-adf-pipeline/v2/ |
    npm run build ./trigger-adf-pipeline/v2/
  displayName: 'npm install & build trigger-adf-pipeline'
