parameters:
  vstsTasks: []

steps:
- ${{ each vstsTask in parameters.vstsTasks }}:
  - script: |
      npm install
    workingDirectory: ${{ vstsTask }}/v2
    displayName: $(vstsTask) - npm install

  - script: |
      npm run build
    workingDirectory: ${{ vstsTask }}/v2
    displayName: $(vstsTask) - npm run build