trigger:
- v2.0

pool:
  vmImage: 'windows-2019'

steps:
- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '10.x'

- script: |
    npm install
    npm run build
  workingDirectory: delete-adf-items/v2
  displayName: 'npm install & build delete-adf-items'

- script: |
    npm install
    npm run build
  workingDirectory: deploy-adf-json/v2
  displayName: 'npm install & build deploy-adf-json'

- script: |
    npm install
    npm run build
  workingDirectory: toggle-adf-trigger/v2
  displayName: 'npm install & build toggle-adf-trigger'

- script: |
    npm install
    npm run build
  workingDirectory: trigger-adf-pipeline/v2
  displayName: 'npm install & build trigger-adf-pipeline'

- script: |
    npm install tfx-cli -g --silent
    tfx extension create --manifest-globs ./vss-extension.json
  displayName: 'install tfx-cli'
